apiVersion: v1
kind: Service
metadata:
  name: devops-test-repo
  labels:
    app: devops-test-repo
spec:
  selector:
    app: devops-test-repo
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP

