apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-test-repo
  labels:
    app: devops-test-repo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: devops-test-repo
  template:
    metadata:
      labels:
        app: devops-test-repo
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: devops-test-config
            - secretRef:
                name: devops-test-db
          resources:
{{- toYaml .Values.resources | nindent 12 }}

