apiVersion: v1
kind: Service
metadata:
  name: devops-test-repo
  labels:
    app: devops-test-repo
spec:
  type: {{ .Values.service.type }}
  selector:
    app: devops-test-repo
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80

